name: nodejs
on:
  # run on push but only for the main branch
  push:
    branches:
      - main
  # run for every pull request
  pull_request: {}
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ðŸ¤ Set Node version from .nvmrc
        run: echo NVMRC=`cat .nvmrc` >> $GITHUB_ENV

      - name: âŽ” Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NVMRC }}

      - name: ðŸ“¥ Download deps
        run: >
          find . -name package.json -maxdepth 10 -type f -not -path "*/node_modules/*" | while read -r file; do
            directory=$(dirname "$file")
            echo "::group:: $directory"
            cd "$directory" && npm install && cd -
            echo "::endgroup::"
          done

      - name: ðŸ§¹ Check code formatting with Prettier
        run: >
          find . -name package.json -maxdepth 10 -type f -not -path "*/node_modules/*" | while read -r file; do
            directory=$(dirname "$file")
            echo "::group:: $directory"
            cd "$directory" 
            npm run format:check || exit 1
            cd -
            echo "::endgroup::"
          done

      - name: ðŸ‘• Lint code with ESLint
        run: >
          find . -name package.json -maxdepth 10 -type f -not -path "*/node_modules/*" | while read -r file; do
            directory=$(dirname "$file")
            echo "::group:: $directory"
            cd "$directory" && npm run lint && cd -
            echo "::endgroup::"
          done
